
title: Iago Leão
url: 'http://iagoleao.com.br'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Iago Leão
tagline: Desenvolvedor Full Stack
pic: profile.jpeg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: contato@iagoleao.com.br
phone: +55 75 9.9114-8678
website: iagoleao.com.br #do not add http://
linkedin: iago-leao
github: iagoleao
twitter: '@iagoleao'

#Update all the sections by editing the files inside _includes folder.
